--03.5.SELECT(Function)_workbook계정
-- 1.
SELECT STUDENT_NO "학번", STUDENT_NAME "이름", TO_CHAR(TO_DATE(ENTRANCE_DATE, 'RR/MM/DD'), 'RRRR-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO ='002'
ORDER BY ENTRANCE_DATE;

-- 2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE NOT PROFESSOR_NAME LIKE '___'
ORDER BY PROFESSOR_NAME;

-- 3.
SELECT PROFESSOR_NAME 이름 , EXTRACT(YEAR FROM SYSDATE) - ('19'||SUBSTR(PROFESSOR_SSN,1,2)) AS "나이"
FROM TB_PROFESSOR
ORDER BY 나이;
-- 나이쪽에 문제있음 

-- 4. 
SELECT SUBSTR(PROFESSOR_NAME,-2,2) 이름
FROM TB_PROFESSOR
ORDER BY PROFESSOR_NO;

-- 5. 40살 1985
SELECT STUDENT_NO, STUDENT_NAME, EXTRACT(YEAR FROM TO_DATE(SUBSTR(ENTRANCE_DATE,1,2), 'RR')) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,2), 'RR'))
FROM TB_STUDENT
WHERE NOT EXTRACT(YEAR FROM TO_DATE(SUBSTR(ENTRANCE_DATE,1,2), 'RR')) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,2), 'RR')) <= 19;


-- 6.
SELECT TO_CHAR(TO_DATE('2020-12-25', 'YYYY-MM-DD'),'DAY') 요일 FROM DUAL;

-- 7.
--2099/10/11
--2049/10/11
--1999/10/11
--2049/10/11

-- 8.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE NOT STUDENT_NO LIKE 'A%'
ORDER BY SUBSTR(STUDENT_NAME,2,2);


-- 9.
SELECT ROUND(AVG(POINT),1)
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10.
-- 그룹바이라 아직 하지않음 
SELECT DISTINCT DEPARTMENT_NO
FROM TB_STUDENT
ORDER BY DEPARTMENT_NO;

-- 11.
SELECT COUNT(*) 
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;;


-- 12.
-- 13.
-- 14.
-- 15.
-- 16.

