-- 1. 
SELECT STUDENT_NAME 학생이름, STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

--2. 
SELECT STUDENT_NAME , STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

--3. 
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS 주소지
FROM TB_STUDENT
WHERE (STUDENT_ADDRESS LIKE '%강원도%' OR STUDENT_ADDRESS LIKE '%경기도%' )AND STUDENT_NO LIKE '9%'
ORDER BY STUDENT_NAME;

--4. 
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM tb_professor P
WHERE P.DEPARTMENT_NO IN (
    SELECT P.DEPARTMENT_NO
    FROM tb_professor P, TB_DEPARTMENT D
    WHERE P.DEPARTMENT_NO = D.DEPARTMENT_NO
    AND DEPARTMENT_NAME = '법학과'
) 
ORDER BY PROFESSOR_SSN;

--5. 
SELECT S.STUDENT_NO , TO_CHAR(POINT,'0.00')
FROM TB_STUDENT S, TB_GRADE G
WHERE TERM_NO = '200402' AND(CLASS_NO = 'C3118100') AND S.STUDENT_NO =G.STUDENT_NO  
ORDER BY POINT DESC;

--6.
SELECT STUDENT_NO , STUDENT_NAME ,DEPARTMENT_NAME
FROM tb_STUDENT P, TB_DEPARTMENT D
WHERE P.DEPARTMENT_NO = D.DEPARTMENT_NO
ORDER BY SUBSTR(STUDENT_NAME,-2,2);

--7. 
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS C, TB_DEPARTMENT D
WHERE C.DEPARTMENT_NO = D.DEPARTMENT_NO
ORDER BY  D.DEPARTMENT_NO, CLASS_TYPE DESC, CLASS_NAME ;

--8.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS C, TB_PROFESSOR P, TB_CLASS_PROFESSOR CP
WHERE C.CLASS_NO = CP.CLASS_NO AND P.PROFESSOR_NO = CP.PROFESSOR_NO
ORDER BY C.DEPARTMENT_NO,  P.PROFESSOR_NO,CLASS_TYPE DESC, CLASS_NAME
;

--9. 
SELECT CLASS_NAME, PROFESSOR_NAME
FROM  
(
SELECT CLASS_NAME, PROFESSOR_NAME, CATEGORY
FROM TB_CLASS C, TB_PROFESSOR P, TB_CLASS_PROFESSOR CP, TB_DEPARTMENT D
WHERE C.CLASS_NO = CP.CLASS_NO AND P.PROFESSOR_NO = CP.PROFESSOR_NO AND C.DEPARTMENT_NO = D.DEPARTMENT_NO
)
WHERE CATEGORY = '인문사회';


-- 10.
SELECT 학번 , 학생이름, ROUND(AVG(평점),1)
FROM (
SELECT S.STUDENT_NO 학번 ,STUDENT_NAME "학생이름" , POINT "평점"
FROM TB_STUDENT S, TB_GRADE G , TB_DEPARTMENT D
WHERE DEPARTMENT_NAME = '음악학과'  AND S.STUDENT_NO =G.STUDENT_NO  AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
)
GROUP BY 학번, 학생이름
ORDER BY 학번;

--11.


SELECT DEPARTMENT_NAME 학과이름 ,STUDENT_NAME "학생이름" , PROFESSOR_NAME "지도교수이름"
FROM TB_STUDENT S, TB_PROFESSOR P, TB_DEPARTMENT D
WHERE STUDENT_NO = 'A313047'  AND D.DEPARTMENT_NO =S.DEPARTMENT_NO  AND S.DEPARTMENT_NO = D.DEPARTMENT_NO AND
P.PROFESSOR_NO = S.COACH_PROFESSOR_NO;

-- 12.

SELECT STUDENT_NAME, TERM_NO  "TERM_NAME" 
FROM TB_STUDENT S, TB_GRADE G, TB_CLASS C
WHERE TERM_NO LIKE '2007%' AND CLASS_NAME = '인간관계론'  AND G.STUDENT_NO =S.STUDENT_NO AND C.CLASS_NO = G.CLASS_NO ;

-- 13. 
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS C , TB_DEPARTMENT D, TB_CLASS_PROFESSOR CP
WHERE  C.DEPARTMENT_NO = D.DEPARTMENT_NO(+) 
--AND P.PROFESSOR_NO = CP.PROFESSOR_NO
AND CP.CLASS_NO(+) = C.CLASS_NO
AND CATEGORY = '예체능'
AND PROFESSOR_NO IS NULL
ORDER BY D.DEPARTMENT_NO, CLASS_TYPE DESC, CLASS_NAME;

--14.
SELECT STUDENT_NAME "학생이름" , NVL(PROFESSOR_NAME,'지도교수 미지정') "지도교수"
FROM TB_STUDENT S, TB_PROFESSOR P, TB_DEPARTMENT D
WHERE DEPARTMENT_NAME = '서반아어학과'  AND D.DEPARTMENT_NO(+) =S.DEPARTMENT_NO  AND S.DEPARTMENT_NO = D.DEPARTMENT_NO(+) AND
P.PROFESSOR_NO(+) = S.COACH_PROFESSOR_NO
ORDER BY STUDENT_NO;


--15.
SELECT S.STUDENT_NO 학번 ,STUDENT_NAME "이름" , DEPARTMENT_NAME "학과 이름", ROUND(AVG(POINT),8) "평점"
FROM TB_STUDENT S, TB_GRADE G , TB_DEPARTMENT D
WHERE ABSENCE_YN = 'N'  AND S.STUDENT_NO =G.STUDENT_NO  AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
GROUP BY S.STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME  
HAVING AVG(POINT)>=4
ORDER BY S.STUDENT_NO;

--16.
SELECT C.CLASS_NO, CLASS_NAME, ROUND(AVG(POINT),8)
FROM TB_STUDENT S, TB_GRADE G , TB_DEPARTMENT D, TB_CLASS C
WHERE DEPARTMENT_NAME = '환경조경학과'  AND S.STUDENT_NO =G.STUDENT_NO  AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
AND C.CLASS_NO = G.CLASS_NO
AND CLASS_TYPE = '전공선택'
GROUP BY C.CLASS_NO, CLASS_NAME
ORDER BY CLASS_NO;

-- 17.

SELECT STUDENT_NAME , STUDENT_ADDRESS 
FROM TB_STUDENT S, TB_DEPARTMENT D
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO AND 
DEPARTMENT_NAME = 
(
SELECT DISTINCT DEPARTMENT_NAME
FROM TB_STUDENT S, TB_GRADE G , TB_DEPARTMENT D
WHERE STUDENT_NAME = '최경희'  AND S.STUDENT_NO =G.STUDENT_NO  AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
)
ORDER BY SUBSTR(STUDENT_NAME,-2,2);


--18.

SELECT STUDENT_NO , STUDENT_NAME
FROM (
    SELECT S.STUDENT_NO "STUDENT_NO", STUDENT_NAME "STUDENT_NAME", ROUND(AVG(POINT),8)
    FROM TB_STUDENT S, TB_GRADE G , TB_DEPARTMENT D, TB_CLASS C
    WHERE DEPARTMENT_NAME = '국어국문학과'  AND S.STUDENT_NO =G.STUDENT_NO  AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
    AND C.CLASS_NO = G.CLASS_NO
    GROUP BY S.STUDENT_NO, STUDENT_NAME
    ORDER BY 3 DESC
)
--WHERE ROWNUM = 1;
FETCH FIRST 5 ROWS ONLY; -- 하위 버전에서는  실행불가 오라클 12버전 이상부터 사용가능

-- 19.
SELECT DEPARTMENT_NAME, ROUND(AVG(POINT),1)
FROM TB_STUDENT S, TB_GRADE G , TB_DEPARTMENT D, TB_CLASS C
WHERE  S.STUDENT_NO =G.STUDENT_NO  AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
AND C.CLASS_NO = G.CLASS_NO 
AND CATEGORY =(
    SELECT DISTINCT CATEGORY
    FROM TB_STUDENT S, TB_GRADE G , TB_DEPARTMENT D, TB_CLASS C
    WHERE DEPARTMENT_NAME = '환경조경학과'  AND S.STUDENT_NO =G.STUDENT_NO  AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
    AND C.CLASS_NO = G.CLASS_NO
    )
GROUP BY DEPARTMENT_NAME
ORDER BY DEPARTMENT_NAME;

-- 순서 완