--1.

INSERT INTO TB_CLASS_TYPE VALUES(01,'전공필수');
INSERT INTO TB_CLASS_TYPE VALUES(02,'전공선택');
INSERT INTO TB_CLASS_TYPE VALUES(03,'교양필수');
INSERT INTO TB_CLASS_TYPE VALUES(04,'교양선택');
INSERT INTO TB_CLASS_TYPE VALUES(05,'논문지도');

-- 2. 
CREATE TABLE TB_STUDENT_INFOR
AS 
(
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
);

-- 3.
DROP TABLE TB_STUDENT_KOR;
CREATE TABLE TB_STUDENT_KOR
AS 
(
SELECT STUDENT_NO, STUDENT_NAME, EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,2),'RR')) 년도, PROFESSOR_NAME
FROM TB_STUDENT S, TB_PROFESSOR P, TB_DEPARTMENT D
WHERE PROFESSOR_NO(+) = COACH_PROFESSOR_NO AND D.DEPARTMENT_NO(+) = S.DEPARTMENT_NO AND DEPARTMENT_NAME = '국어국문학과'
);

CREATE TABLE TB_STUDENT_KOR2
AS 
(
SELECT STUDENT_NO, STUDENT_NAME, EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,2),'RR')) 년도, PROFESSOR_NAME
FROM TB_STUDENT S, TB_PROFESSOR P, TB_DEPARTMENT D
WHERE PROFESSOR_NO(+) = COACH_PROFESSOR_NO AND D.DEPARTMENT_NO(+) = S.DEPARTMENT_NO AND DEPARTMENT_NAME = '국어국문학과'
);
-- NULL 추가 

-- 4.
UPDATE TB_DEPARTMENT
SET CAPACITY = CAPACITY * 1.1;

--5.
UPDATE TB_STUDENT
SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE STUDENT_NO = 'A413042';

--6.
UPDATE TB_STUDENT
SET STUDENT_SSN = SUBSTR(STUDENT_SSN,1,6);

--7. 
UPDATE TB_GRADE
SET POINT = 3.5
WHERE TERM_NO = 200501 AND STUDENT_NO = (
SELECT STUDENT_NO 
FROM TB_STUDENT S, TB_DEPARTMENT D
WHERE STUDENT_NAME = '김명훈' AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
AND DEPARTMENT_NAME = '의학과'
)
AND CLASS_NO = 
(
SELECT CLASS_NO
FROM TB_CLASS
WHERE CLASS_NAME = '피부생리학')
;

SELECT STUDENT_NO 
FROM TB_STUDENT S, TB_DEPARTMENT D
WHERE STUDENT_NAME = '김명훈' AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
AND DEPARTMENT_NAME = '의학과';

--8.
DELETE FROM TB_GRADE
WHERE STUDENT_NO IN (
SELECT S.STUDENT_NO
FROM TB_STUDENT S, TB_GRADE G
WHERE S.STUDENT_NO = G.STUDENT_NO AND 
ABSENCE_YN = 'Y'
)


